name: expat_assistant
description: A Flutter project about HCMC expat assistant.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  convex_bottom_bar: ^3.0.0
  line_icons: ^2.0.1
  bloc: ^7.0.0
  flutter_bloc: ^7.1.0
  outline_search_bar: ^2.1.1
  google_fonts: ^2.1.0
  cupertino_progress_bar: ^0.2.0
  step_progress_indicator: ^1.0.0
  adaptive_dialog: ^1.0.0
  sweetsheet: ^0.3.1
  camera_camera: ^2.0.2
  flutter_sound: ^8.1.4
  permission_handler: ^8.0.1
  bubble: ^1.2.1
  location: ^4.2.1
  google_maps_flutter: ^2.0.6
  geocode: ^1.0.1
  image_picker: ^0.8.0+3
  camera: ^0.8.1+3
  photo_view: ^0.11.1
  expandable_text: ^2.2.0
  syncfusion_flutter_datepicker: ^19.1.67-beta
  table_calendar: ^3.0.0
  material_floating_search_bar: ^0.3.4
  getwidget: ^2.0.2
  dio: ^4.0.0
  equatable: ^2.0.3
  formz: ^0.4.0
  hive: ^2.0.4
  flutter_native_splash: ^1.2.0
  flowder: ^0.2.0
  android_external_storage: ^0.1.0
  assets_audio_player: ^3.0.3+3
  ionicons: ^0.1.2
  intl: ^0.17.0
  cached_network_image: ^3.0.0
  url_launcher: ^6.0.7
  event_bus: ^2.0.0
  path_provider: ^2.0.2
  agora_rtc_engine: ^4.0.2
  flutter_html: ^2.1.0
  multi_select_flutter: ^4.0.0
  pin_code_fields: ^7.2.0
  mailer: ^5.0.1
  extended_image: ^4.1.0
  flutter_rating_bar: ^4.0.0
  sliding_sheet: ^0.5.0
  firebase_storage: ^10.0.1
  firebase_core: ^1.4.0
  firebase_analytics: ^8.2.0
  multiselect_formfield: ^0.1.6
  select_form_field: ^2.1.0
  textfield_tags: ^1.4.0
  direct_select_flutter: ^1.1.1
  momo_vn: ^2.0.1
  firebase_auth: ^3.0.1
  flutter_countdown_timer: ^4.1.0
  rsa_encrypt: ^2.0.0
  asn1lib: ^1.0.2
  random_string: ^2.3.1
  syncfusion_flutter_calendar: ^19.2.51
  fl_chart: ^0.36.3
  google_place: ^0.4.3
  onesignal_flutter: ^3.2.0
  latlong2: ^0.8.0
  gallery_view: ^1.0.0+1
  image_viewer: ^1.5.0
  badges: ^2.0.1
  timeago: ^3.1.0

dev_dependencies:
  build_runner: ^2.0.4
  hive_generator: ^1.1.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo_spash.png
  fullscreen: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/app_logo.png
    - assets/images/logo_spash.png
    - assets/images/app_icon.png
    - assets/images/facebook_logo.png
    - assets/images/google_logo.png
    - assets/images/google_white_logo.png
    - assets/images/facebook_white_logo.png
    - assets/images/profile.png
    - assets/images/folder.png
    - assets/images/oops.png
    - assets/images/conversation_icon.png
    - assets/images/vocabulary_icon.png
    - assets/images/utilities_banner.jpg
    - assets/images/utilities_banner_2.png
    - assets/images/finish_lesson.png
    - assets/images/sign_up_logo.png
    - assets/images/demo_lesson.png
    - assets/images/demo_vocabulary.png
    - assets/images/demo_conversation.png
    - assets/images/demo_event.png
    - assets/images/demo_thumb.jpg
    - assets/images/demo_channel.png
    - assets/images/demo_news.png
    - assets/images/vietnamese_logo.png
    - assets/images/expert_logo.png
    - assets/images/time_call.png
    - assets/images/schedule_done.png
    - assets/images/success_pay.png
    - assets/images/demo_expert.jpg
    - assets/images/camera_food_logo.png
    - assets/images/feedback.png
    - assets/images/no_photo.png
    - assets/images/map.png
    - assets/images/demo_food.jpg
    - assets/images/April.png
    - assets/images/August.png
    - assets/images/December.png
    - assets/images/February.png
    - assets/images/January.png
    - assets/images/July.png
    - assets/images/June.png
    - assets/images/March.png
    - assets/images/May.png
    - assets/images/November.png
    - assets/images/October.png
    - assets/images/September.png
    - assets/test/demo_sound.mp3
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Literata
       fonts:
         - asset: assets/fonts/Literata-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
